package com.reachout.slackapp.UTIL;

public class Constants {
	static String accessToken;
	public static final String clientID = Messages.getString("Constants.0"); //$NON-NLS-1$
	public static final String clientSecret = Messages.getString("Constants.1"); //$NON-NLS-1$
	public static final String scope=Messages.getString("Constants.2"); //$NON-NLS-1$
	public static final String redirect_uri=Messages.getString("Constants.3"); //$NON-NLS-1$
	public static final String state=Messages.getString("Constants.4"); //$NON-NLS-1$
	public static final String FORUMCHANNELNAME=Messages.getString("Constants.5"); //$NON-NLS-1$
	public static final String SUGGESTIONSCHANNELNAME=Messages.getString("Constants.6"); //$NON-NLS-1$
	public static final String GRIEVANCESCHANNELNAME=Messages.getString("Constants.7"); //$NON-NLS-1$
	public static final String attachments=Messages.getString("Constants.8");  //$NON-NLS-1$
	public static final String oaccessURL=Messages.getString("Constants.9");  //$NON-NLS-1$
	public static final String createGroupURL=Messages.getString("Constants.10");  //$NON-NLS-1$
	public static final String postMessageURL=Messages.getString("Constants.11"); //$NON-NLS-1$
	public static final String successMessagePostedReply=Messages.getString("Constants.12"); //$NON-NLS-1$
	public static final String ANONYMITY_FALLBACK_MSG=Messages.getString("Constants.13"); //$NON-NLS-1$
	public static final String ANONYMITY_TITLE=Messages.getString("Constants.14"); //$NON-NLS-1$
	public static final String ANONYMITY_TEXT=Messages.getString("Constants.15"); //$NON-NLS-1$
	public static final String ANONYMITY_DEFAULT_ATTACHMENT_TYPE=Messages.getString("Constants.16"); //$NON-NLS-1$
	public static final String ANONYMITY_CALLBACK_ID=Messages.getString("Constants.17"); //$NON-NLS-1$
	public static final String PRIVACY_FALLBACK_MSG=Messages.getString("Constants.18"); //$NON-NLS-1$
	public static final String PRIVACY_TITLE=Messages.getString("Constants.19"); //$NON-NLS-1$
	public static final String PRIVACY_TEXT=Messages.getString("Constants.20"); //$NON-NLS-1$
	public static final String PRIVACY_DEFAULT_ATTACHMENT_TYPE=Messages.getString("Constants.21"); //$NON-NLS-1$
	public static final String PRIVACY_CALLBACK_ID=Messages.getString("Constants.22"); //$NON-NLS-1$
	public static final String DEPARTMENT_FALLBACK_MSG=Messages.getString("Constants.23"); //$NON-NLS-1$
	public static final String DEPARTMENT_TITLE=Messages.getString("Constants.24"); //$NON-NLS-1$
	public static final String DEPARTMENT_TEXT=Messages.getString("Constants.25"); //$NON-NLS-1$
	public static final String DEPARTMENT_DEFAULT_ATTACHMENT_TYPE=Messages.getString("Constants.26"); //$NON-NLS-1$
	public static final String DEPARTMENT_CALLBACK_ID=Messages.getString("Constants.27"); //$NON-NLS-1$
	public static final String FIRST_MESSAGE_TEXT=Messages.getString("Constants.28"); //$NON-NLS-1$
	public static final String SECOND_MESSAGE_TEXT=Messages.getString("Constants.29"); //$NON-NLS-1$
	public static final String THIRD_MESSAGE_TEXT=Messages.getString("Constants.30"); //$NON-NLS-1$
	public static final String TEK_ADMIN_NAME=Messages.getString("Constants.31"); //$NON-NLS-1$
	public static final String TEK_ADMIN_TEXT=Messages.getString("Constants.32"); //$NON-NLS-1$
	public static final String TEK_ADMIN_TYPE=Messages.getString("Constants.33"); //$NON-NLS-1$
	public static final String TEK_ADMIN_VALUE=Messages.getString("Constants.34"); //$NON-NLS-1$
	public static final String VENKAT_ORG_NAME=Messages.getString("Constants.35"); //$NON-NLS-1$
	public static final String VENKAT_ORG_TEXT=Messages.getString("Constants.36"); //$NON-NLS-1$
	public static final String VENKAT_ORG_TYPE=Messages.getString("Constants.37"); //$NON-NLS-1$
	public static final String VENKAT_ORG_VALUE=Messages.getString("Constants.38"); //$NON-NLS-1$
	public static final String UMESH_ORG_NAME=Messages.getString("Constants.39"); //$NON-NLS-1$
	public static final String UMESH_ORG_TEXT=Messages.getString("Constants.40"); //$NON-NLS-1$
	public static final String UMESH_ORG_TYPE=Messages.getString("Constants.41"); //$NON-NLS-1$
	public static final String UMESH_ORG_VALUE=Messages.getString("Constants.42"); //$NON-NLS-1$
	public static final String SATYA_ORG_NAME=Messages.getString("Constants.43"); //$NON-NLS-1$
	public static final String SATYA_ORG_TEXT=Messages.getString("Constants.44"); //$NON-NLS-1$
	public static final String SATYA_ORG_TYPE=Messages.getString("Constants.45"); //$NON-NLS-1$
	public static final String SATYA_ORG_VALUE=Messages.getString("Constants.46"); //$NON-NLS-1$
	public static final String AMULYA_ORG_NAME=Messages.getString("Constants.47"); //$NON-NLS-1$
	public static final String AMULYA_ORG_TEXT=Messages.getString("Constants.48"); //$NON-NLS-1$
	public static final String AMULYA_ORG_TYPE=Messages.getString("Constants.49"); //$NON-NLS-1$
	public static final String AMULYA_ORG_VALUE=Messages.getString("Constants.50"); //$NON-NLS-1$
	public static final String RAJAN_ORG_NAME=Messages.getString("Constants.51"); //$NON-NLS-1$
	public static final String RAJAN_ORG_TEXT=Messages.getString("Constants.52"); //$NON-NLS-1$
	public static final String RAJAN_ORG_TYPE=Messages.getString("Constants.53"); //$NON-NLS-1$
	public static final String RAJAN_ORG_VALUE=Messages.getString("Constants.54"); //$NON-NLS-1$
	
	public static final String HR_DEPARTMENT_ORG_NAME=Messages.getString("Constants.55"); //$NON-NLS-1$
	public static final String HR_DEPARTMENT_ORG_TEXT=Messages.getString("Constants.56"); //$NON-NLS-1$
	public static final String HR_DEPARTMENT_ORG_TYPE=Messages.getString("Constants.57"); //$NON-NLS-1$
	public static final String HR_DEPARTMENT_ORG_VALUE=Messages.getString("Constants.58"); //$NON-NLS-1$
	public static final String FINANCE_DEPARTMENT_ORG_NAME=Messages.getString("Constants.59"); //$NON-NLS-1$
	public static final String FINANCE_DEPARTMENT_ORG_TEXT=Messages.getString("Constants.60"); //$NON-NLS-1$
	public static final String FINANCE_DEPARTMENT_ORG_TYPE=Messages.getString("Constants.61"); //$NON-NLS-1$
	public static final String FINANCE_DEPARTMENT_ORG_VALUE=Messages.getString("Constants.62"); //$NON-NLS-1$
	public static final String PUBLIC_NAME=Messages.getString("Constants.63"); //$NON-NLS-1$
	public static final String PUBLIC_TEXT=Messages.getString("Constants.64"); //$NON-NLS-1$
	public static final String PUBLIC_TYPE=Messages.getString("Constants.65"); //$NON-NLS-1$
	public static final String PUBLIC_VALUE=Messages.getString("Constants.66"); //$NON-NLS-1$
	public static final String PRIVATE_NAME=Messages.getString("Constants.67"); //$NON-NLS-1$
	public static final String PRIVATE_TEXT=Messages.getString("Constants.68"); //$NON-NLS-1$
	public static final String PRIVATE_TYPE=Messages.getString("Constants.69"); //$NON-NLS-1$
	public static final String PRIVATE_VALUE=Messages.getString("Constants.70"); //$NON-NLS-1$
	public static final String NAMED_NAME=Messages.getString("Constants.71"); //$NON-NLS-1$
	public static final String NAMED_TEXT=Messages.getString("Constants.72"); //$NON-NLS-1$
	public static final String NAMED_TYPE=Messages.getString("Constants.73"); //$NON-NLS-1$
	public static final String NAMED_VALUE=Messages.getString("Constants.74");	 //$NON-NLS-1$
	public static final String ANONYMOUS_NAME=Messages.getString("Constants.75"); //$NON-NLS-1$
	public static final String ANONYMOUS_TEXT=Messages.getString("Constants.76"); //$NON-NLS-1$
	public static final String ANONYMOUS_TYPE=Messages.getString("Constants.77"); //$NON-NLS-1$
	public static final String ANONYMOUS_VALUE=Messages.getString("Constants.78");	 //$NON-NLS-1$
}